name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image with deegree 3.3
      run: docker build . --file ./3.3/Dockerfile -t tfr42/deegree:3.3.21 -t tfr42/deegree:3.3
