name: Docker Image CI

on:
  schedule:
  - cron: "0 1 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-3_3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.3
      uses: docker/build-push-action@v4
      with:
        context: ./3.3
        platforms: linux/amd64,linux/arm64
        push: true
        tags: tfr42/deegree:3.3.21,tfr42/deegree:3.3
  build-3_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.4
      uses: docker/build-push-action@v4
      with:
        context: ./3.4
        platforms: linux/amd64,linux/arm64
        push: true
        tags: tfr42/deegree:3.4.34,tfr42/deegree:3.4
  build-3_5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.5
      uses: docker/build-push-action@v4
      with:
        context: ./3.5
        platforms: linux/amd64,linux/arm64
        push: true
        tags: tfr42/deegree:3.5.2,tfr42/deegree:3.5,tfr42/deegree:latest
  build-3_5_jdk17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.5 with JDK 17
        uses: docker/build-push-action@v4
        with:
          context: ./3.5
          file: DockerfileJdk17
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tfr42/deegree:3.5.2-jdk17-tomcat10,tfr42/deegree:3.5-jdk17-tomcat10,tfr42/deegree:3.5-jdk17