name: Docker Image CI

on:
  schedule:
    - cron: "15 3,15 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-3_3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.3
      uses: docker/build-push-action@v6
      with:
        context: ./3.3
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: tfr42/deegree:3.3.21,tfr42/deegree:3.3
  build-3_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.4
      uses: docker/build-push-action@v6
      with:
        context: ./3.4
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: tfr42/deegree:3.4.35,tfr42/deegree:3.4
  build-3_5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push v3.5
      uses: docker/build-push-action@v6
      with:
        context: ./3.5
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        push: true
        tags: tfr42/deegree:3.5.16,tfr42/deegree:3.5,tfr42/deegree:3.5-jdk11
  build-3_5_jdk17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.5 with JDK 17
        uses: docker/build-push-action@v6
        with:
          context: ./3.5
          file: ./3.5/DockerfileJdk17
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: tfr42/deegree:3.5.16-jdk17-tomcat10,tfr42/deegree:3.5-jdk17-tomcat10,tfr42/deegree:3.5-jdk17
  build-3_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.6 with JDK 17
        uses: docker/build-push-action@v6
        with:
          context: ./3.6
          file: ./3.6/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: tfr42/deegree:3.6,tfr42/deegree:3.6.0,tfr42/deegree:3.6-jdk17-tomcat10,tfr42/deegree:3.6-jdk17,tfr42/deegree:latest